packages:
    - 'playground/*'
    - 'src/*'
    - 'docs'

catalog:
    "@eslint/js": "^9.20.0"
    "@hotwired/stimulus": "^3.2.2"
    "@hotwired/turbo": "^8.0.12"
    "@sveltejs/vite-plugin-svelte": "^5.0.3"
    "@symfony/ux-autocomplete": "^2.24.0"
    "@symfony/ux-chartjs": "^2.24.0"
    "@symfony/ux-cropperjs": "^2.24.0"
    "@symfony/ux-dropzone": "^2.24.0"
    "@symfony/ux-notify": "^2.24.0"
    "@symfony/ux-react": "^2.24.0"
    "@symfony/ux-svelte": "^2.24.0"
    "@symfony/ux-swup": "^2.24.0"
    "@symfony/ux-translator": "^2.24.0"
    "@symfony/ux-turbo": "^2.24.0"
    "@symfony/ux-typed": "^2.24.0"
    "@symfony/ux-vue": "^2.24.0"
    "@symfony/ux-lazy-image": "^2.24.0"
    "@symfony/ux-live-component": "^2.24.0"
    "@symfony/ux-toggle-password": "^2.24.0"
    "@symfony/stimulus-bridge": "^4.0.0"
    "@types/node": "^22.13.1"
    "@types/react": "^18.3.18"
    "@types/react-dom": "^18.3.5"
    "@vitejs/plugin-legacy": "^6.0.1"
    "@vitejs/plugin-react": "^4.3.4"
    "@vitejs/plugin-vue": "^5.2.1"

    "globals": "^15.14.0"
    "prettier": "^3.4.2"
    "react": "^18.3.1"
    "react-dom": "^18.3.1"
    "svelte": "^5.25.0"
    "typescript": "^5.7.3"
    "typescript-eslint": "^8.23.0"
    "vite": "^6.1.0"
    "vite-plugin-inspect": "^10.1.1"
    "vite-plugin-static-copy": "^2.2.0"
    "vue": "^3.5.13"

